# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - resource-quota.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - mongodb.yaml
  - secrets.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

commonLabels:
  app: mern-demo

